spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/logistics_express?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
    show-sql: true
  data:
    web:
      pageable:
        prefix: p_
      sort:
        sort-parameter: s_sort
  redis:
    host: localhost
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    ignore-missing-migrations: true
    validate-on-migrate: false
    clean-on-validation-error: true
mylib:
  casbin:
    enforcer:
      enableLog: true
