spring:
  profiles:
    active: test
mylib:
  casbin:
    enforcer:
      enableLog: true
logging:
  level:
    com.dduptop.logistics.server.service: debug
    com.dduptop.service.document.client: debug
    com.dduptop.service.auth.client: debug
ems:
  auth:
    appIds:
      # 武汉仲裁委
      - 620e65bc427c32702917fd8dfaebb2df
    secrets:
      - 9XHfSozZPfuwqlpcVMb6qkizEI5RlrzC
    enables:
      - true
  create-order:
    url: https://211.156.195.17/iwaybillno-web/a/iwaybill/receive
    parent-id: key123xydJDPT
  classification:
    url: http://211.156.195.187:8086/ceshi_csb_broker
    api: routInfoQueryForPDD
    version: 1.0.0
    accessKey: dd979a77b2a44e54b65f01dcbc0bae04
    secretKey: kCZfusS4Zn300MTnYtIlWzhdoE8=
    wpCode: whzcwyh-EMS
  order-line:
    url: http://211.156.195.29/querypush-twswn/mailTrack/queryMailTrackWn/plus
    app-key: AFAB71AB1F1E1353
  batch-no:
    url: https://211.156.195.17/iwaybillno-web/a/iwaybillBatch/receive
    key: key123xydJDPT
    customer-no: 1100035161086
  order-insert:
    url: https://211.156.195.17/ebiistandard-job/a/ChinaPostApi/OrderCreate
    parent-id: key123xydJDPT
    sender-no: 1100035161086
