server:
  port: 8080
  servlet:
    context-path: /logistics-express
spring:
  redis:
    host: redis
micro-service:
  app-id: DbpZtLoZDwPEbNyBxF9MZjXbOMUtKJzV
  secret: KLpBRe8BqhIGTJ6ldj7qaWQaKmVIpcvk
  base-url: https://msgtest.dduptop.com
  system: logistics
  auth-service-config:
    url: /auth
  document-service-config:
    url: /document
mylib:
  casbin:
    enforcer:
      enableLog: false
ems:
  auth:
    appIds:
      # 武汉仲裁委
      - 620e65bc427c32702917fd8dfaebb2df
    secrets:
      - 9XHfSozZPfuwqlpcVMb6qkizEI5RlrzC
    enables:
      - true
  create-order:
    url: https://211.156.195.17/iwaybillno-web/a/iwaybill/receive
    parent-id: key123xydJDPT
  classification:
    url: https://211.156.195.14:443/csb_jidi1_1
    api: routInfoQueryForPDD
    version: 1.0.0
    accessKey: 980ee03f63ef470ea5a249633133fbe9
    secretKey: C3GY4wxUob7j/OEg1PN7Z8y7gKQ=
    wpCode: whzcwyh-EMS
  order-line:
    url: http://211.156.195.35/querypush-twswn/mailTrack/queryMailTrackWn/plus
    app-key: AFAB71AB1F1E1353
  batch-no:
    url: https://211.156.195.15/iwaybillno-web/a/iwaybillBatch/receive
    key: VU849DhAhOUj
    customer-no: 1100035161086
  order-insert:
    url: https://211.156.195.15/ebiistandard-job/a/ChinaPostApi/OrderCreate
    parent-id: VU849DhAhOUj
    sender-no: 1100035161086
