spring:
  profiles:
    active: dev
  redis:
    host: localhost
mylib:
  casbin:
    enforcer:
      enableLog: true
logging:
  level:
    com.dduptop.logistics.server.service: debug
    com.dduptop.service.document.client: debug
    com.dduptop.service.auth.client: debug
